import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.QA_PGLITE_PATH);
const db = new PGlite();
const id = n => `00000000-0000-0000-0000-${String(n).padStart(12, '0')}`;
const rpc = async (name, args) => (await db.query(`select public.${name}(${args.map((_, i) => '$' + (i + 1)).join(',')}) result`, args)).rows[0].result;
try {
  await db.exec(`create schema auth;create role authenticated;create role anon;
    create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
    create table auth.users(id uuid primary key,email text);
    create table profiles(id uuid primary key,display_name text,name text);
    create table persons(id uuid primary key,preferred_name text,display_name text);
    create table book_projects(id uuid primary key,owner_user_id uuid,purchaser_user_id uuid,subject_person_id uuid,title text,created_at timestamptz,family_id uuid);
    create table project_supporters(id uuid primary key,book_project_id uuid,supporter_user_id uuid,status text,can_operate_recording boolean,can_edit_book_text boolean,can_build_book boolean,meta_json jsonb);
    create table family_subject_bindings(person_id uuid,subject_user_id uuid,claimed_at timestamptz);
    create table voice_publications(id uuid primary key,public_id text,book_project_id uuid,book_title text,book_subtitle text,subject_name text,status text,published_at timestamptz);
    create table book_completion_candidates(id uuid,publication_id uuid,state text);
    create table story_sharing_preferences(id uuid,book_project_id uuid,family_sharing_enabled boolean,selected_sharing_enabled boolean);
    create table story_share_recipients(sharing_preference_id uuid,recipient_user_id uuid,status text,recipient_phase text,source text);
    create table family_memberships(family_id uuid,user_id uuid,status text);
    create table admin_audit_logs(admin_user_id uuid,action text,entity_type text,entity_id uuid,metadata jsonb);
    create function is_tateyoko_admin() returns boolean language sql as $$select auth.uid()='${id(99)}'$$;
    create function family_managed(p uuid) returns boolean language sql as $$select current_setting('test.family',true)='true'$$;
    create function family_creator(p uuid,u uuid) returns boolean language sql as $$select u='${id(1)}' or (u='${id(2)}' and current_setting('test.consent',true)='true')$$;
    create function get_admin_project_preview(p uuid) returns jsonb language sql as $$select jsonb_build_object('project',jsonb_build_object('id',p),'answers','[]'::jsonb)$$;
    insert into auth.users values('${id(1)}','mother@example.test'),('${id(2)}','daughter@example.test'),('${id(3)}','viewer@example.test'),('${id(99)}','admin@example.test');
    insert into profiles values('${id(2)}','娘',null);
    insert into persons values('${id(4)}','母',null);
    insert into book_projects values('${id(5)}','${id(1)}','${id(2)}','${id(4)}','母の物語',now(),null);
    insert into project_supporters values('${id(6)}','${id(5)}','${id(2)}','active',true,true,true,'{}');
    insert into voice_publications values('${id(7)}','${'a'.repeat(48)}','${id(5)}','母の本','','母','published',now());
    insert into book_completion_candidates values('${id(8)}','${id(7)}','completed');
    insert into story_sharing_preferences values('${id(9)}','${id(5)}',false,true);
    insert into story_share_recipients values('${id(9)}','${id(3)}','active','live','selected');
    set test.uid='${id(99)}';set test.family='false';set test.consent='false';`);
  await db.exec(await readFile('supabase/migrations/202609230008_admin_customer_experience.sql', 'utf8'));
  let daughter = await rpc('get_admin_customer_experience', [id(2)]);
  assert.equal(daughter.actor_id, id(99));
  assert.equal(daughter.target_account_id, id(2));
  assert.equal(daughter.capability, 'read');
  assert.equal(daughter.owned_projects.length, 0);
  assert.equal(daughter.supported_projects.length, 1);
  assert.equal(daughter.bookshelf.length, 1);
  assert.equal(daughter.bookshelf[0].paper_book_ordered, true);
  assert.equal((await rpc('get_admin_customer_project_stories', [id(2), id(5)])).project.id, id(5));
  assert.equal(await rpc('admin_customer_can_read_publication', [id(2), id(7)]), true);
  let viewer = await rpc('get_admin_customer_experience', [id(3)]);
  assert.equal(viewer.bookshelf.length, 1);
  await assert.rejects(rpc('get_admin_customer_project_stories', [id(3), id(5)]), /cannot read/);
  await db.exec(`update voice_publications set status='disabled' where id='${id(7)}'`);
  viewer = await rpc('get_admin_customer_experience', [id(3)]);
  assert.equal(viewer.bookshelf.length, 0);
  assert.equal(await rpc('admin_customer_can_read_publication', [id(3), id(7)]), false);
  assert.equal(await rpc('admin_customer_can_read_publication', [id(2), id(7)]), true);
  await db.exec(`update project_supporters set status='paused' where id='${id(6)}'`);
  daughter = await rpc('get_admin_customer_experience', [id(2)]);
  assert.equal(daughter.supported_projects.length, 0);
  await assert.rejects(rpc('get_admin_customer_project_stories', [id(2), id(5)]), /cannot read/);
  assert.equal(await rpc('admin_customer_can_read_publication', [id(2), id(7)]), false);
  await db.exec(`set test.uid='${id(3)}'`);
  await assert.rejects(rpc('get_admin_customer_experience', [id(2)]), /Admin access/);
  console.log('PASS customer review: actor/target/read split, supporter-only home, bookshelf set, viewer scope, revoked supporter, admin audit gate');
} finally { await db.close(); }
