import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {familyRollout} from '../../src/lib/familyRollout.js';
import {createFamilyApi} from '../../src/lib/familyConnection.js';
const prod='https://wquxjeqkumossjxehdop.supabase.co',test='https://zpswxefgfabzvxdbtyvq.supabase.co';
assert.equal(familyRollout({VITE_SUPABASE_URL:prod,VITE_FAMILY_CONNECTION_TEST:'true'}).enabled,false);
const release=familyRollout({VITE_SUPABASE_URL:prod,VITE_FAMILY_PRODUCTION_ENABLED:'true'});
assert.deepEqual(release,{test:false,enabled:true,subjectConnection:false,delivery:false});
assert.equal(familyRollout({VITE_SUPABASE_URL:test,VITE_FAMILY_PRODUCTION_ENABLED:'true'}).enabled,false);
assert.equal(familyRollout({VITE_SUPABASE_URL:prod+'.invalid',VITE_FAMILY_PRODUCTION_ENABLED:'true'}).enabled,false);
assert.throws(()=>createFamilyApi({supabaseUrl:prod}));
assert.ok(createFamilyApi({supabaseUrl:prod},{VITE_FAMILY_PRODUCTION_ENABLED:'true'}));
const compiled=await build({entryPoints:['supabase/functions/_shared/family-release.ts'],bundle:true,write:false,format:'esm'});
const m=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
const env={};const get=k=>env[k];
assert.equal(m.familyEnvironmentEnabled(get),false);
env.SUPABASE_URL=prod;env.FAMILY_TEST_ENABLED='true';assert.equal(m.familyEnvironmentEnabled(get),false);
env.FAMILY_PRODUCTION_ENABLED='true';assert.equal(m.familyEnvironmentEnabled(get),true);
env.SUPABASE_URL=test;delete env.FAMILY_TEST_ENABLED;assert.equal(m.familyEnvironmentEnabled(get),false);
env.FAMILY_TEST_ENABLED='true';assert.equal(m.familyEnvironmentEnabled(get),true);
let managed=true,allowed=true,fail=false;
const admin={rpc:async name=>({data:name==='family_managed'?managed:allowed,error:fail?Error('DB unavailable'):null})};
assert.equal(await m.requireFamilyRelease(admin,'p','u',get),true);
await assert.rejects(()=>m.requireFamilyRelease(admin,'p','',get));
allowed=false;await assert.rejects(()=>m.requireFamilyRelease(admin,'p','u',get));
fail=true;await assert.rejects(()=>m.requireFamilyRelease(admin,'p','u',get));fail=false;
managed=false;delete env.FAMILY_TEST_ENABLED;
assert.equal(await m.requireFamilyRelease(admin,'self','u',get),false,'Ordinary self flow does not require family flag');
console.log('PASS explicit environment gates, frontend not authorization, DB deny/failure, self independence, C/delivery default OFF');
