import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {db,as,admin,val,id} from './family-connection.sql.test.mjs';
try {
 await admin('');
 await db.exec(await readFile(new URL('../../supabase/migrations/202609210003_production_supporter.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../../supabase/migrations/202609210004_production_start_audit_key.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../../supabase/migrations/202609210005_separate_production_mode_and_authority.sql',import.meta.url),'utf8'));
 await as(1);
 assert.equal(await val('select family_creator($1) value',[id(20)]),false,'No silent upgrade of old supporter');
 await assert.rejects(()=>db.query('select family_confirm_production_support($1,$2,false)',[id(20),id(1)]),/consent/);
 await as(3);
 await assert.rejects(()=>db.query('select family_confirm_production_support($1,$2,true)',[id(20),id(3)]),/Forbidden/);
 await as(1);
 const consent=await val('select family_confirm_production_support($1,$2,true) value',[id(20),id(1)]);
 assert.ok(consent);
 assert.equal(await val('select family_confirm_production_support($1,$2,true) value',[id(20),id(1)]),consent,'Retry retains original consent timestamp and actor');
 assert.equal(await val('select family_creator($1) value',[id(20)]),true);
 assert.equal(await val('select family_subject($1) value',[id(20)]),false,'Supporter never becomes subject');
 assert.equal(await val('select can_manage_book_cover($1) value',[id(20)]),true);
 const w=await val('select family_journey($1) value',[id(20)]);
 assert.equal(w.role,'supporter');assert.equal(w.can_produce,true);assert.equal(w.production_mode,'supporter');
 assert.ok(w.answers.some(a=>a.private),'Production accesses private material independently of Viewer sharing');
 assert.ok((await db.query('select id from answers where book_project_id=$1',[id(20)])).rows.length);
 assert.ok((await db.query('select name from storage.objects')).rows.some(r=>r.name.endsWith('/old-private.mp4')));
 await assert.rejects(()=>db.query('update answers set transcript_raw=$1 where id=$2 returning id',['ATTACK',id(40)]).then(r=>{assert.equal(r.rows.length,0);throw Error('blocked');}),/blocked/);
 await admin('');
 const c=await val('select to_jsonb(c) value from family_production_consents c where id=$1',[consent]);
 assert.equal(c.person_id,id(12));assert.equal(c.confirmed_by,id(1));assert.equal(c.supporter_user_id,id(1));assert.ok(c.confirmed_at);
 assert.equal(c.project_id,id(20));assert.equal(c.subject_intent_confirmed,true);assert.ok(c.supporter_id);
 const audit=await val("select to_jsonb(e) value from family_production_events e where consent_id=$1 and event='consent'",[consent]);
 assert.equal(audit.actor_id,id(1));assert.equal(audit.person_id,id(12));assert.equal(audit.project_id,id(20));assert.equal(audit.supporter_id,c.supporter_id);assert.ok(audit.created_at);
 await assert.rejects(()=>db.query("select family_assert_operation($1,$2,'manage',$3)",[id(20),id(1),id(41)]),/Forbidden answer/);
 await as(2);
 await db.query('select family_revoke_production_support($1,$2)',[id(20),id(1)]);
 await as(1);
 assert.equal(await val('select family_creator($1) value',[id(20)]),false);
 assert.equal(await val('select family_supporter($1) value',[id(20)]),false,'Subject stop cannot fall back to legacy supporter access');
 await assert.rejects(()=>db.query('select family_journey($1)',[id(20)]),/Forbidden/);
 await assert.rejects(()=>db.query("select family_reserve_upload($1,'audio','mp4')",[id(20)]),/Forbidden/);
 await assert.rejects(()=>db.query('select family_confirm_production_support($1,$2,true)',[id(20),id(1)]),/Subject approval|Forbidden/);
 await as(2);
 await db.query('select family_confirm_production_support($1,$2,true,$3)',[id(20),id(1),'self']);
 await as(1);
 assert.equal(await val('select family_creator($1) value',[id(20)]),true,'Self-led subject can grant full production support');
 assert.equal(await val('select can_confirm_experience_intent($1) value',[id(20)]),true,'Self-led mode does not remove consented production authority');
 await admin('');await db.query("update family_subject_bindings set production_mode='supporter' where person_id=$1",[id(12)]);
 await as(3);assert.equal(await val('select family_creator($1) value',[id(20)]),false,'Mode alone never grants authority');
 await as(3);
 assert.equal(await val('select family_creator($1) value',[id(20)]),false);
 assert.equal((await db.query('select id from answers where book_project_id=$1',[id(20)])).rows.length,0);
 await admin('');
 await db.query("update story_sharing_preferences set selected_sharing_enabled=true where book_project_id=$1",[id(20)]);
 await db.query("insert into story_share_recipients(sharing_preference_id,recipient_user_id,source) select id,$2,'direct' from story_sharing_preferences where book_project_id=$1",[id(20),id(3)]);
 await as(3);
 assert.equal(await val('select shared_story_recipient_can_view($1) value',[id(20)]),true);
 assert.equal(await val('select family_answer_visible($1) value',[id(40)]),false,'An authorized Viewer still cannot read a private story');
 await as(1);await db.query('select family_set_answer_sharing($1,true)',[id(40)]);
 await as(3);
 assert.equal(await val('select family_answer_visible($1) value',[id(40)]),true,'Explicitly shared story remains readable to its Viewer');
 await assert.rejects(()=>db.query('select family_set_answer_sharing($1,false)',[id(40)]),/Forbidden/);
 await as(1);await db.query('select family_set_answer_sharing($1,false)',[id(40)]);
 await admin('');
 await db.query("insert into auth.users(id,email) values($1,'fixture-friend@example.invalid')",[id(4)]);
 await db.exec("insert into commerce_products(product_code,display_name,amount_jpy) values('premium_hardcover_v1','TEST premium',30000),('gift_package_v1','TEST package',5000) on conflict do nothing");
 // Both entry paths keep a single Person and Project without a subject Account.
 for(const [index,label] of ['trial','direct'].entries()){
  await as(1);
  const p=await val('select family_create($1,true,$2) value',[`Fixture ${label}`,id(200+index)]);
  await db.query('select family_confirm_production_support($1,$2,true)',[p,id(1)]);
  await admin('');
  const person=await val('select subject_person_id value from book_projects where id=$1',[p]);
  assert.equal(await val('select subject_user_id value from family_subject_bindings where person_id=$1',[person]),null);
  await db.query(`insert into commerce_orders(id,book_project_id,purchaser_user_id,order_type,product_code,status,amount_subtotal,amount_total,base_book_amount)
   values($1,$2,$3,'self','self_book_v1','checkout_pending',49800,49800,49800)`,[id(210+index),p,id(1)]);
  const contract=await val('select register_experience_contract($1) value',[id(210+index)]);assert.equal(contract.guarantee_days,45);
  await db.query("update commerce_orders set status='paid' where id=$1",[id(210+index)]);
  await db.query('select confirm_experience_payment($1,now())',[id(210+index)]);
  await as(1);
  await assert.rejects(()=>db.query('select start_paid_starting_chapter($1,false)',[p]),/subject/);
  await db.query('select start_paid_starting_chapter($1,true)',[p]);
  await admin('');
  assert.equal(await val('select main_experience_started_at value from experience_contracts where book_project_id=$1',[p]),null,'Starting chapter does not end guarantee');
  await db.query("update book_projects set onboarding_ritual_step='chapter_complete' where id=$1",[p]);
  await as(1);await db.query('select start_main_experience($1,true)',[p]);
  await db.query('select start_main_experience($1,true)',[p]);
  await admin('');
  const events=(await db.query("select event,actor_id,person_id,supporter_id,consent_id from family_production_events where project_id=$1 and event in('starting_chapter','main_experience')",[p])).rows;
  assert.equal(events.length,2,'Idempotent audit for both paid boundaries');
  assert.ok(events.every(e=>e.actor_id===id(1)&&e.person_id===person&&e.supporter_id&&e.consent_id));
  assert.equal(await val('select main_started_by value from experience_contracts where book_project_id=$1',[p]),id(1));
  await db.query(`insert into answers(id,user_id,book_project_id,subject_person_id,sequence_order,transcript_edited,access_override,user_question_id,question_id)
   values($1,$2,$3,$4,$5,'Private production story','private_forever',(select id from user_questions where book_project_id=$3 limit 1),'TEST_Q1')`,[id(220+index),id(1),p,person,500+index]);
  await as(1);
  const work=await val('select save_book_selection($1,$2,0) value',[p,[id(220+index)]]);
  const confirmed=await val('select confirm_book_work($1,$2,true) value',[p,work.revision]);
  assert.equal(confirmed.confirmed_by,id(1));assert.equal(confirmed.snapshot.subject.id,person);
  assert.equal(confirmed.snapshot.answers[0].access_override,'private_forever','Book selection does not publish to Viewer');
  await assert.rejects(()=>db.query('select save_book_selection($1,$2,$3)',[p,[],work.revision]),/confirmed/);
  await admin('');
  assert.equal(await val('select subject_user_id value from family_subject_bindings where person_id=$1',[person]),null,'Completion did not invent mother Account');
  if(index===0){
   await db.query("insert into project_supporters(book_project_id,supporter_user_id,granted_by_user_id,status,can_operate_recording,can_manage_photos) values($1,$2,$3,'active',true,true)",[p,id(4),id(1)]);
   await as(4);await db.query('select family_confirm_production_support($1,$2,true)',[p,id(4)]);
   assert.equal(await val('select family_creator($1) value',[p]),true,'Production access is a role, not a daughter/owner exception');
   assert.equal((await val('select get_book_work($1) value',[p])).id,confirmed.id);
   await admin('');await db.query("update book_projects set access_status='paid' where id=$1",[p]);
   await db.exec("set role service_role");
   const friendOrder=await val("select create_book_commerce_order($1,$2,null,0,0,false,'{}'::jsonb) value",[id(4),p]);
   assert.equal(friendOrder.order.purchaser_user_id,id(4));assert.equal(friendOrder.order.book_project_id,p);
   await admin('');
   assert.equal(await val('select owner_user_id value from book_projects where id=$1',[p]),id(1));
   await as(1);
   const invite=await val('select family_issue_invite($1,$2) value',[p,'09000000003']);
   await as(3);await db.query('select family_claim_invite($1,true)',[invite.token]);
   const attached=await val('select family_journey($1) value',[p]);assert.equal(attached.person_id,person);assert.equal(attached.role,'subject');
   const sameWork=await val('select get_book_work($1) value',[p]);assert.equal(sameWork.id,confirmed.id);assert.deepEqual(sameWork.answer_ids,[id(220)]);
   assert.equal(attached.production_mode,'supporter','Subject joins without being forced to change the progress preference');
   await admin('');
   assert.equal(await val('select order_id value from experience_contracts where book_project_id=$1',[p]),id(210));
   assert.equal(await val('select purchaser_user_id value from commerce_orders where id=$1',[id(210)]),id(1));
   await as(1);assert.equal(await val('select family_creator($1) value',[p]),true,'Mother join does not remove the production supporter');
   await assert.rejects(()=>db.query('select family_list_production_supporters($1)',[p]),/Subject access/);
   await as(3);const members=await val('select family_list_production_supporters($1) value',[p]);
   assert.ok(members.some(x=>x.supporter_user_id===id(1)&&x.confirmed_at));
   await db.query('select family_revoke_production_support($1,$2)',[p,id(1)]);
   assert.ok(!(await val('select family_list_production_supporters($1) value',[p])).some(x=>x.supporter_user_id===id(1)));
   await admin('');const revoked=await val("select to_jsonb(e) value from family_production_events e where project_id=$1 and event='revoke'",[p]);
   assert.equal(revoked.actor_id,id(3));assert.equal(revoked.person_id,person);assert.ok(revoked.created_at);
   await as(1);assert.equal(await val('select family_creator($1) value',[p]),false);
   await assert.rejects(()=>db.query('select family_confirm_production_support($1,$2,true)',[p,id(1)]),/Forbidden|Subject approval/);
   await assert.rejects(()=>db.query('select get_book_work($1)',[p]),/Forbidden|forbidden|authorized|access|owner/i);
  }
 }
 console.log('PASS production supporter consent, no-subject paid/main/book, 45-day guarantee, audits, immutable work, identity separation, private access, revocation and Viewer guards');
} catch(e) {console.error({message:e.message,where:e.where});process.exitCode=1;} finally { await db.close(); }
