import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.QA_PGLITE_PATH || '@electric-sql/pglite');
const db = new PGlite();
const id = n => `00000000-0000-0000-0000-${String(n).padStart(12, '0')}`;
await db.exec(`
create schema auth; create schema storage;
create role authenticated; create role anon;
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
set test.uid = '${id(1)}';
create table book_projects(id uuid primary key, status text, owner_user_id uuid, subject_person_id uuid, family_id uuid);
create table project_supporters(book_project_id uuid, supporter_user_id uuid, status text, can_operate_recording boolean);
create table user_questions(id uuid primary key, book_project_id uuid, is_active boolean, question_id text, sequence_order int, status text, answered_at timestamptz);
create table answers(id uuid primary key, user_id uuid, book_project_id uuid, speaker_person_id uuid, subject_person_id uuid, user_question_id uuid, question_id text, sequence_order int, transcript_raw text, transcript_clean text, transcript_readable text, transcript_essay text, transcript_edited text, selected_style text, ai_mirror text, snippet text, meta_json jsonb, created_at timestamptz default now());
create table media_assets(id uuid primary key default gen_random_uuid(), answer_id uuid, user_id uuid, family_id uuid, book_project_id uuid, person_id uuid, asset_type text, storage_path text, meta_json jsonb, unique(answer_id,asset_type,storage_path));
create table storage.objects(bucket_id text, name text);
insert into book_projects values ('${id(10)}','active','${id(2)}','${id(3)}','${id(4)}');
insert into project_supporters values ('${id(10)}','${id(1)}','active',true);
insert into user_questions values ('${id(20)}','${id(10)}',true,'Q1',1,'pending',null),('${id(21)}','${id(10)}',true,'Q2',2,'pending',null);
`);
await db.exec(await readFile(new URL('../../supabase/migrations/202609140001_append_supporter_recording.sql', import.meta.url), 'utf8'));
const audioPath = n => `${id(1)}/${id(n)}/part-01.mp4`;
for (const n of [30,31,32]) await db.query('insert into storage.objects values ($1,$2)', ['audio', audioPath(n)]);
const save = (n, raw, readable, q = 20, path = audioPath(n)) => db.query('select append_supporter_recording($1,$2,$3,$4,$5,$6,$7,$8,$9) as id', [id(10),id(q),id(n),raw,readable,'','readable',[path],600]);
assert.equal((await save(30,'first raw','first edited')).rows[0].id,id(30));
const firstMedia = (await db.query('select id from media_assets')).rows[0].id;
await db.exec(`update media_assets set meta_json=meta_json || '{"custom":"keep"}';`);
assert.equal((await save(31,'second raw','second edited')).rows[0].id,id(30));
await save(31,'second raw','second edited'); // Response lost/retry must not duplicate.
const answer = (await db.query('select * from answers')).rows[0];
assert.equal(answer.transcript_raw,'first raw\n\nsecond raw');
assert.equal(answer.transcript_edited,'first edited\n\nsecond edited');
assert.equal(answer.meta_json.duration_seconds,1200);
assert.equal(answer.user_id,id(2),'The owner remains the mother, not the supporter');
const media = (await db.query('select * from media_assets order by (meta_json->>\'part\')::int')).rows;
assert.equal(media.length,2);
assert.equal(media[0].id,firstMedia,'Existing asset identity is preserved');
assert.equal(media[0].meta_json.custom,'keep');
assert.equal(media[0].meta_json.total_parts,2);
assert.equal(media[1].storage_path,audioPath(31));
assert.equal((await db.query('select status from user_questions where id=$1',[id(21)])).rows[0].status,'pending');
await assert.rejects(save(31,'x','x',21),/already belongs/);
await assert.rejects(save(32,'x','x',20,`${id(2)}/${id(32)}/part-01.mp4`),/Forbidden/);
await assert.rejects(save(33,'x','x'),/Uploaded audio/);
await db.exec(`set test.uid = '${id(2)}';`);
await assert.rejects(save(32,'x','x'),/access is not allowed/);
await db.exec(`set test.uid = '${id(1)}'; update project_supporters set can_operate_recording=false;`);
await assert.rejects(save(32,'x','x'),/access is not allowed/);
await db.exec('update project_supporters set can_operate_recording=true;');
await db.exec(`create function fail_audio_insert() returns trigger language plpgsql as $$ begin raise exception 'Simulated media failure'; end; $$;
create trigger qa_fail before insert on media_assets for each row execute function fail_audio_insert();`);
await assert.rejects(save(32,'must roll back','must roll back'),/Simulated media failure/);
assert.equal((await db.query('select transcript_edited from answers')).rows[0].transcript_edited,'first edited\n\nsecond edited','A failed asset save rolls back text changes too');
await db.exec('drop trigger qa_fail on media_assets;');
await save(32,'',''); // Speech processing is not required for audio preservation.
assert.equal((await db.query('select count(*)::int as n from media_assets')).rows[0].n,3);
assert.equal((await db.query('select transcript_edited from answers')).rows[0].transcript_edited,'first edited\n\nsecond edited');
assert.equal((await db.query("select has_function_privilege('anon','append_supporter_recording(uuid,uuid,uuid,text,text,text,text,text[],numeric)','execute') as ok")).rows[0].ok,false);
await db.close();
console.log('PASS supporter SQL: atomic append, original audio/metadata retained, idempotent retry, ownership, authorization, other-question isolation, audio-only save');
