import assert from 'node:assert/strict';
import {snapshotToWebBook,webBookSections,webBookStorySequence,webBookAudioSequence} from '../../src/lib/webBook.js';
import {compareMediaChronologically} from '../../supabase/functions/_shared/media-order.js';
const snap={cover:{title:'Paper title',footer_text:'2026.09'},subject:{display_name:'Person'},answers:[{id:'b',user_question_id:'q2',transcript_edited:'finished'}],questions:[{id:'q2',question_id:'TY_ONB02'}],media:[],web_intro:{answers:[{id:'a',user_question_id:'q1'}],questions:[{id:'q1',question_id:'TY_ONB01'}],media:[{id:'m',answer_id:'a',asset_type:'audio',url:'sample',meta_json:{part:1}}]}};
const pub=snapshotToWebBook(snap),s=webBookSections(pub);
assert.equal(pub.title,'Paper title');assert.equal(s.name.sourceAnswerId,'a');assert.equal(s.now[0].transcript,'finished');assert.equal(s.now[1],undefined);assert.equal(s.opening,undefined);assert.equal(s.closing,undefined);assert.equal(s.other.length,0);
assert.equal(webBookSections({items:[{order:1,question:'legacy',audio:[{}]}]}).other.length,1);
const videoOnly=webBookSections({items:[{order:1,sourceAnswerId:'v',questionId:'TY_CLOSING01',slot:'closing'}],videos:[{sourceAnswerId:'v'}]});assert.ok(videoOnly.closing);assert.ok(videoOnly.videoFor(videoOnly.closing));
assert.equal(webBookSections({items:[]}).themes.length,0);
const dedup=snapshotToWebBook({...snap,web_intro:{answers:snap.answers,questions:snap.questions}});assert.equal(dedup.items.length,1);
console.log('PASS Web Book: stable identity, cover source, optional omissions, frozen intro, legacy access, video-only, dedup');
const media=[{id:'new',created_at:'2026-09-23T01:00:00Z',meta_json:{}},{id:'original',created_at:'2026-09-22T01:00:00Z',meta_json:{part:1}},{id:'append',created_at:'2026-09-22T02:00:00Z',meta_json:{part:2}}];
assert.deepEqual(media.sort(compareMediaChronologically).map(m=>m.id),['original','append','new']);
assert.deepEqual([{meta_json:{part:2}},{meta_json:{part:1}}].sort(compareMediaChronologically).map(m=>m.meta_json.part),[1,2]);
assert.equal(snapshotToWebBook({...snap,answers:[{...snap.answers[0],transcript_edited:'元の語りと語り足しを統合した現行文章'}]}).items[0].transcript,'元の語りと語り足しを統合した現行文章');
console.log('PASS queue chronology and single integrated current transcript');
const story=(order,questionId,extra={})=>({order,sourceAnswerId:`a${order}`,questionId,transcript:'text',audio:[{assetIndex:0}],...extra});
const book={items:[story(9,'TY_CLOSING01'),story(5,'q2',{themeCode:'ty_theme_childhood'}),story(1,'TY_ONB01'),story(2,'TY_ONB02'),story(4,'q1',{themeCode:'ty_theme_childhood'}),story(3,'TY_ONB04'),story(6,'q3',{themeCode:'ty_theme_youth',audio:[]}),story(10,'empty',{transcript:'',audio:[]})]};
const sequence=webBookStorySequence(book);
assert.deepEqual(sequence.map(e=>e.id),['a3','a2','a4','a5','a6','a9']);
assert.equal(sequence[2].nextId,'a5');assert.equal(sequence[3].nextId,'a6');assert.equal(sequence[4].previousId,'a5');
assert.equal(sequence.at(-1).isLast,true);assert.equal(sequence.filter(e=>e.isLast).length,1);
assert.deepEqual(webBookAudioSequence(sequence).map(e=>e.id),['a3','a2','a4','a5','a9']);
assert.equal(webBookStorySequence({items:book.items.filter(i=>i.questionId!=='TY_CLOSING01')}).at(-1).id,'a6');
assert.equal(webBookStorySequence({items:[]}).length,0);
const videoBook={items:[story(1,'TY_ONB04',{audio:[]})],videos:[{sourceAnswerId:'a1',slot:'opening',videoIndex:0}]};
assert.equal(webBookStorySequence(videoBook).length,1);assert.equal(webBookAudioSequence(webBookStorySequence(videoBook)).length,0);
assert.equal(webBookStorySequence({videos:[{videoIndex:1,slot:'closing',title:'ending'}]}).at(-1).kind,'ending');
assert.equal(new Set(sequence.map(e=>e.id)).size,sequence.length);
console.log('PASS single story sequence: order, links, chapter transitions, empty answers, name exclusion, text/video-only, final fallback');
